"use client";

import { useState } from "react";
import { XMarkIcon } from "@heroicons/react/24/outline";
const CreateScoreForm = ({ onClose, onCreate }) => {
  const [form, setForm] = useState({ sport: "Cricket", teamA: "", teamB: "", scoreA: "", scoreB: "", status: "live", location: "", description: "" });
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (e) => { e.preventDefault(); if (!form.teamA || !form.teamB) return; onCreate(form); };
  return <div className="fixed inset-0 z-[90] grid place-items-end bg-black/40 p-0 backdrop-blur-sm sm:place-items-center sm:p-6" onClick={onClose}><form onSubmit={submit} onClick={(e) => e.stopPropagation()} className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-t-[28px] bg-[var(--bg-card)] p-5 sm:rounded-[28px] sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--brand)]">Community update</p><h2 className="text-xl font-black text-[var(--text-heading)]">Post a score</h2></div><button type="button" onClick={onClose}><XMarkIcon className="h-6 w-6" /></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["sport","Sport"],["teamA","Team or player A"],["teamB","Team or player B"],["scoreA","Score A"],["scoreB","Score B"],["location","Location (optional)"]].map(([key,label]) => key === "sport" ? <label className="text-xs font-bold text-[var(--text-muted)]" key={key}>{label}<select value={form.sport} onChange={(e)=>set(key,e.target.value)} className="mt-1.5 w-full rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-input)] p-2.5 text-sm text-[var(--text-body)]">{["Cricket","Football","Badminton","Tennis"].map(x=><option key={x}>{x}</option>)}</select></label> : <label className="text-xs font-bold text-[var(--text-muted)]" key={key}>{label}<input value={form[key]} onChange={(e)=>set(key,e.target.value)} className="mt-1.5 w-full rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-input)] p-2.5 text-sm text-[var(--text-body)]" required={key === "teamA" || key === "teamB"} /></label>)}</div><label className="mt-3 block text-xs font-bold text-[var(--text-muted)]">Match status<select value={form.status} onChange={(e)=>set("status",e.target.value)} className="mt-1.5 w-full rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-input)] p-2.5 text-sm text-[var(--text-body)]"><option value="live">Live</option><option value="completed">Completed</option><option value="upcoming">Upcoming</option></select></label><label className="mt-3 block text-xs font-bold text-[var(--text-muted)]">Commentary<textarea value={form.description} onChange={(e)=>set("description",e.target.value)} className="mt-1.5 min-h-20 w-full rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-input)] p-2.5 text-sm text-[var(--text-body)]" placeholder="What should the community know?" /></label><button className="mt-5 w-full rounded-xl bg-[var(--brand)] py-3 text-sm font-bold text-[var(--on-brand)]">Share score</button></form></div>;
};
export default CreateScoreForm;
