"use client";

import { useState } from "react";
import { PhotoIcon, XMarkIcon } from "@heroicons/react/24/outline";
const CreateStoryForm = ({ onClose, onCreate }) => {
 const [sport, setSport] = useState("Football"), [caption,setCaption] = useState("");
 return <div className="fixed inset-0 z-[90] grid place-items-end bg-black/40 p-0 backdrop-blur-sm sm:place-items-center sm:p-6" onClick={onClose}><form onSubmit={(e)=>{e.preventDefault();onCreate({sport,caption: caption || "A new moment from the game"});}} onClick={(e)=>e.stopPropagation()} className="w-full max-w-lg rounded-t-[28px] bg-[var(--bg-card)] p-5 sm:rounded-[28px] sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--brand)]">24-hour update</p><h2 className="text-xl font-black text-[var(--text-heading)]">Create a story</h2></div><button type="button" onClick={onClose}><XMarkIcon className="h-6 w-6" /></button></div><label className="mt-5 flex h-40 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[var(--brand-border)] bg-[var(--brand-soft)] text-center"><PhotoIcon className="h-8 w-8 text-[var(--brand)]" /><span className="mt-2 text-sm font-bold text-[var(--text-body)]">Add an image or video</span><span className="mt-1 text-xs text-[var(--text-muted)]">Media upload preview</span><input className="sr-only" type="file" accept="image/*,video/*" /></label><label className="mt-4 block text-xs font-bold text-[var(--text-muted)]">Sport<select value={sport} onChange={(e)=>setSport(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-input)] p-2.5 text-sm text-[var(--text-body)]">{["Cricket","Football","Badminton","Tennis"].map(x=><option key={x}>{x}</option>)}</select></label><label className="mt-3 block text-xs font-bold text-[var(--text-muted)]">Overlay text<textarea value={caption} onChange={(e)=>setCaption(e.target.value)} className="mt-1.5 min-h-20 w-full rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-input)] p-2.5 text-sm text-[var(--text-body)]" placeholder="Add a match moment…" /></label><button className="mt-5 w-full rounded-xl bg-[var(--brand)] py-3 text-sm font-bold text-[var(--on-brand)]">Share story</button></form></div>;
};
export default CreateStoryForm;
