"use client";

import { ShareIcon, XMarkIcon } from "@heroicons/react/24/outline";

const ScoreDetailsModal = ({ score, onClose }) => {
  if (!score) return null;
  const completed = score.status === "completed";
  const events = score.events || ["Match centre is being updated."];
  const stats = score.stats || [["Community reactions", String(score.likes), `${score.comments} comments`]];
  return <div className="fixed inset-0 z-[90] flex items-end bg-black/40 p-0 backdrop-blur-sm sm:items-center sm:justify-center sm:p-6" onClick={onClose} role="dialog" aria-modal="true" aria-label="Match details">
    <section onClick={(event) => event.stopPropagation()} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-[28px] bg-[var(--bg-card)] p-5 shadow-2xl sm:rounded-[28px] sm:p-7">
      <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--brand)]">{score.sport} · {completed ? "Full time" : score.status}</p><h2 className="mt-1 text-xl font-black text-[var(--text-heading)]">{score.teamA.name} vs {score.teamB.name}</h2><p className="mt-1 text-sm text-[var(--text-muted)]">{score.matchTime} · {score.location}</p></div><div className="flex gap-2"><button type="button" aria-label="Share match" className="rounded-xl bg-[var(--bg-secondary)] p-2 text-[var(--text-body)]"><ShareIcon className="h-5 w-5" /></button><button type="button" onClick={onClose} aria-label="Close" className="rounded-xl bg-[var(--bg-secondary)] p-2 text-[var(--text-body)]"><XMarkIcon className="h-5 w-5" /></button></div></div>
      <div className="mt-6 overflow-hidden rounded-2xl border border-[var(--border-subtle)]"><div className="grid grid-cols-[1fr_auto_1fr] items-center bg-[var(--bg-secondary)] p-5 text-center"><div><p className="font-bold text-[var(--text-heading)]">{score.teamA.name}</p><strong className="mt-2 block text-3xl text-[var(--text-heading)]">{score.teamA.score || "–"}</strong></div><span className="px-4 text-xs font-bold text-[var(--text-muted)]">{completed ? "FINAL" : "vs"}</span><div><p className="font-bold text-[var(--text-heading)]">{score.teamB.name}</p><strong className="mt-2 block text-3xl text-[var(--text-heading)]">{score.teamB.score || "–"}</strong></div></div>{completed && <div className="border-t border-[var(--brand-border)] bg-[var(--brand-soft)] px-4 py-3 text-center"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[var(--brand)]">Result</p><p className="mt-0.5 text-sm font-black text-[var(--text-heading)]">{score.result || "Match completed"}</p></div>}</div>
      {score.scoreline?.length > 0 && <div className="mt-6"><h3 className="font-black text-[var(--text-heading)]">Score breakdown</h3><div className="mt-3 overflow-hidden rounded-xl border border-[var(--border-subtle)]"><div className="grid grid-cols-[1fr_auto_auto] bg-[var(--bg-secondary)] px-4 py-2 text-[10px] font-bold uppercase tracking-wide text-[var(--text-muted)]"><span>Round</span><span className="px-4">{score.teamA.name}</span><span>{score.teamB.name}</span></div>{score.scoreline.map((round) => <div className="grid grid-cols-[1fr_auto_auto] border-t border-[var(--border-light)] px-4 py-2.5 text-sm" key={round.label}><span className="font-medium text-[var(--text-body)]">{round.label}</span><strong className="px-4 text-[var(--text-heading)]">{round.a}</strong><strong className="text-[var(--text-heading)]">{round.b}</strong></div>)}</div></div>}
      <div className={`mt-6 grid gap-3 ${stats.length > 1 ? "sm:grid-cols-3" : ""}`}>{stats.map(([label, a, b]) => <div key={label} className="rounded-xl border border-[var(--border-subtle)] p-3 text-center"><p className="text-[10px] font-bold uppercase tracking-wide text-[var(--text-muted)]">{label}</p><p className="mt-1 font-black text-[var(--text-heading)]">{a} <span className="text-[var(--text-faint)]">—</span> {b}</p></div>)}</div>
      <div className="mt-6"><h3 className="font-black text-[var(--text-heading)]">Match timeline</h3><ol className="mt-3 space-y-3 border-l-2 border-[var(--brand-border)] pl-4">{events.map((event) => <li className="relative text-sm text-[var(--text-body)]" key={event}><i className="absolute -left-[22px] top-1.5 h-2.5 w-2.5 rounded-full bg-[var(--brand)]" />{event}</li>)}</ol></div>
      <div className="mt-6 border-t border-[var(--border-light)] pt-5"><h3 className="font-black text-[var(--text-heading)]">Community comments</h3><div className="mt-3 flex gap-2"><input aria-label="Add a comment" className="min-w-0 flex-1 rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-input)] px-3 py-2 text-sm outline-none focus:border-[var(--brand)]" placeholder="Add a match reaction…" /><button type="button" className="rounded-xl bg-[var(--brand)] px-4 text-sm font-bold text-[var(--on-brand)]">Post</button></div></div>
    </section>
  </div>;
};
export default ScoreDetailsModal;
